<?php
define('company','Regard Group LLC');
define('address','Address:');
define('address_text','23/2 Yervand Kochar str, Yerevan, Armenia');
define('contacts','Contacts:');
define('telephone','Tel./Fax.:');
define('telephone_short','Phone:');
define('telephone_short_text','+ 374  94 53 00 71');
define('telephone_text',' +374 60 53 00 71');
define('mobile','Mob.:');
define('mobile_text','+374 55 43 55 95 ');
define('email','Email:');
define('email_text','info@regardtrave<wbr/>l.com');
define('url','URL:');
define('url_text',' www.RegardTravel<wbr/>.com');
define('title','THANKS FOR YOUR REQUEST');
define('from','From:');
define('from_text','Regard Travel');
define('to','To:');
define('to_text','Ani Plaza hotel Yerevan');
define('voucher','VOUCHER');
define('invoice','INVOICE');
define('guests','Guest(s) Name(s):');
define('guest_count','Number of guests:');
define('room_types','Type of room(s):');
define('check_in','Check in date:');
define('check_out','Check out date:');
define('extra_services','Our service includes:');
define('hotel_booking_info','night(s)  accommodation in');
define('night', 'night');
define('breakfast','Breakfast');
define('airport_transfer','Airport transfer');
define('sim_card','Sim card');
define('city_tour','City Tour');
define('room','Room(s)');
define('per_night','Per Night');
define('transfer_f','Transfer:');
define('transfer_f_amount','Free');
define('total_amount','Total amount');
define('bank_account','Bank Account');
define('payment_status','Payment Status');
define('lunch','Lunch');
define('dinner','Dinner');
define('confirmed','CONFIRMED');